version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Trendora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tokitoclaude0907@
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Trendora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Tokitoclaude0907@
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
