version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Trendora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tokitoclaude0907@
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Trendora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Tokitoclaude0907@
