spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d2mc38bipnbc73ckoot0-a.oregon-postgres.render.com:5432/trendora_db}
    username: ${SPRING_DATASOURCE_USERNAME:trendora_db_user}
    password: ${SPRING_DATASOURCE_PASSWORD:oiv7goYzKnewfEHGTWgYqGyWrxxMNqf8}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: 8070e45fb4a8d31c5d4c23e0444ccda0761b82ad28e6ec8e6a14b1c8ec8ffaa7
    expiration-time: 1800000
